### ISSUE TITLE
parse_recurrence_params_by_type method returning wrong :monthweek

### ISSUE THREAD

**Issue by mrsousa** [angelic/schedule_fu#1]
Hello, 
the method parse_recurrence_params_by_type uses "(start_date.mday - 1) / 7" to fill up the :monthweek symbol but it will only works right for months that the first day is Sunday.

I have no solution yet.

David Sousa

**Comment by mrsousa** [comment]
I have come up with a solution that I think that works.
Max Williams suggest a solution for this at http://railsforum.com/viewtopic.php?id=33423, but when I was cheeking it out I found 2 problems.

The final solution is: 

```
class Date
    def week_of_month
        self.wday != 0 ? (cweek = self.cweek) : (cweek = self.cweek + 1) 
        self.at_beginning_of_month.wday != 0 ? (cweek_at_beginning_of_month = elf.at_beginning_of_month.cweek) : (cweek_at_beginning_of_month =  elf.at_beginning_of_month.cweek + 1) 
        return cweek - cweek_at_beginning_of_month if cweek -  week_at_beginning_of_month > 0
        cweek
    end
end  
```

It may not be the driest way. But works (I think, at least). 
If someone could test it would be great!

David Sousa

**Comment by angelic** [comment]
This is currently working as intended. In :monthweek, we care more about whether it is the first, second, etc. Monday (or whatever) day of the week. We don't really care if it is truly the first week with a Sunday-Saturday week. The monthweek in CalendarDate is calculated the same way, and the sql view using CalendarEvent matches these up for monthly and yearly events.
