### ISSUE TITLE
Massive SQL Query & Mysql::Error: Lock wait timeout exceeded; try restarting

### ISSUE THREAD

**Issue by jspooner** [angelic/schedule_fu#2]
I get this Mysql::Error a lot when running my cucumber test.  Has anyone else run into this error too?

SQL (0.8ms)   ROLLBACK
  CalendarDate Load (0.2ms)   SELECT \* FROM `calendar_dates` WHERE (`calendar_dates`.`value` = '2010-10-26') LIMIT 1
  CalendarDate Create (0.0ms)   Mysql::Error: Lock wait timeout exceeded; try restarting transaction: INSERT INTO `calendar_dates` (`month`, `lastweek`, `value`, `monthday`, `monthweek`, `weekday`) VALUES(10, 0, '2010-10-23', 23, 3, 6)

SELECT \* FROM `calendar_dates` WHERE (value IN ('2009-10-23','2009-10-24','2009-10-25','2009-10-26','2009-10-27','2009-10-28','2009-10-29','2009-10-30','2009-10-31','2009-11-01','2009-11-02','2009-11-03','2009-11-04','2009-11-05','2009-11-06','2009-11-07','2009-11-08','2009-11-09','2009-11-10','2009-11-11','2009-11-12','2009-11-13','2009-11-14','2009-11-15','2009-11-16','2009-11-17','2009-11-18','2009-11-19','2009-11-20','2009-11-21','2009-11-22','2009-11-23','2009-11-24','2009-11-25','2009-11-26','2009-11-27','2009-11-28','2009-11-29','2009-11-30','2009-12-01','2009-12-02','2009-12-03','2009-12-04','2009-12-05','2009-12-06','2009-12-07','2009-12-08','2009-12-09','2009-12-10','2009-12-11','2009-12-12','2009-12-13','2009-12-14','2009-12-15','2009-12-16','2009-12-17','2009-12-18','2009-12-19','2009-12-20','2009-12-21','2009-12-22','2009-12-23','2009-12-24','2009-12-25','2009-12-26','2009-12-27','2009-12-28','2009-12-29','2009-12-30','2009-12-31','2010-01-01','2010-01-02','2010-01-03','2010-01-04','2010-01-05','2010-01-06','2010-01-07','2010-01-08','2010-01-09','2010-01-10','2010-01-11','2010-01-12','2010-01-13','2010-01-14','2010-01-15','2010-01-16','2010-01-17','2010-01-18','2010-01-19','2010-01-20','2010-01-21','2010-01-22','2010-01-23','2010-01-24','2010-01-25','2010-01-26','2010-01-27','2010-01-28','2010-01-29','2010-01-30','2010-01-31','2010-02-01','2010-02-02','2010-02-03','2010-02-04','2010-02-05','2010-02-06','2010-02-07','2010-02-08','2010-02-09','2010-02-10','2010-02-11','2010-02-12','2010-02-13','2010-02-14','2010-02-15','2010-02-16','2010-02-17','2010-02-18','2010-02-19','2010-02-20','2010-02-21','2010-02-22','2010-02-23','2010-02-24','2010-02-25','2010-02-26','2010-02-27','2010-02-28','2010-03-01','2010-03-02','2010-03-03','2010-03-04','2010-03-05','2010-03-06','2010-03-07','2010-03-08','2010-03-09','2010-03-10','2010-03-11','2010-03-12','2010-03-13','2010-03-14','2010-03-15','2010-03-16','2010-03-17','2010-03-18','2010-03-19','2010-03-20','2010-03-21','2010-03-22','2010-03-23','2010-03-24','2010-03-25','2010-03-26','2010-03-27','2010-03-28','2010-03-29','2010-03-30','2010-03-31','2010-04-01','2010-04-02','2010-04-03','2010-04-04','2010-04-05','2010-04-06','2010-04-07','2010-04-08','2010-04-09','2010-04-10','2010-04-11','2010-04-12','2010-04-13','2010-04-14','2010-04-15','2010-04-16','2010-04-17','2010-04-18','2010-04-19','2010-04-20','2010-04-21','2010-04-22','2010-04-23','2010-04-24','2010-04-25','2010-04-26','2010-04-27','2010-04-28','2010-04-29','2010-04-30','2010-05-01','2010-05-02','2010-05-03','2010-05-04','2010-05-05','2010-05-06','2010-05-07','2010-05-08','2010-05-09','2010-05-10','2010-05-11','2010-05-12','2010-05-13','2010-05-14','2010-05-15','2010-05-16','2010-05-17','2010-05-18','2010-05-19','2010-05-20','2010-05-21','2010-05-22','2010-05-23','2010-05-24','2010-05-25','2010-05-26','2010-05-27','2010-05-28','2010-05-29','2010-05-30','2010-05-31','2010-06-01','2010-06-02','2010-06-03','2010-06-04','2010-06-05','2010-06-06','2010-06-07','2010-06-08','2010-06-09','2010-06-10','2010-06-11','2010-06-12','2010-06-13','2010-06-14','2010-06-15','2010-06-16','2010-06-17','2010-06-18','2010-06-19','2010-06-20','2010-06-21','2010-06-22','2010-06-23','2010-06-24','2010-06-25','2010-06-26','2010-06-27','2010-06-28','2010-06-29','2010-06-30','2010-07-01','2010-07-02','2010-07-03','2010-07-04','2010-07-05','2010-07-06','2010-07-07','2010-07-08','2010-07-09','2010-07-10','2010-07-11','2010-07-12','2010-07-13','2010-07-14','2010-07-15','2010-07-16','2010-07-17','2010-07-18','2010-07-19','2010-07-20','2010-07-21','2010-07-22','2010-07-23','2010-07-24','2010-07-25','2010-07-26','2010-07-27','2010-07-28','2010-07-29','2010-07-30','2010-07-31','2010-08-01','2010-08-02','2010-08-03','2010-08-04','2010-08-05','2010-08-06','2010-08-07','2010-08-08','2010-08-09','2010-08-10','2010-08-11','2010-08-12','2010-08-13','2010-08-14','2010-08-15','2010-08-16','2010-08-17','2010-08-18','2010-08-19','2010-08-20','2010-08-21','2010-08-22','2010-08-23','2010-08-24','2010-08-25','2010-08-26','2010-08-27','2010-08-28','2010-08-29','2010-08-30','2010-08-31','2010-09-01','2010-09-02','2010-09-03','2010-09-04','2010-09-05','2010-09-06','2010-09-07','2010-09-08','2010-09-09','2010-09-10','2010-09-11','2010-09-12','2010-09-13','2010-09-14','2010-09-15','2010-09-16','2010-09-17','2010-09-18','2010-09-19','2010-09-20','2010-09-21','2010-09-22','2010-09-23','2010-09-24','2010-09-25','2010-09-26','2010-09-27','2010-09-28','2010-09-29','2010-09-30','2010-10-01','2010-10-02','2010-10-03','2010-10-04','2010-10-05','2010-10-06','2010-10-07','2010-10-08','2010-10-09','2010-10-10','2010-10-11','2010-10-12','2010-10-13','2010-10-14','2010-10-15','2010-10-16','2010-10-17','2010-10-18','2010-10-19','2010-10-20','2010-10-21','2010-10-22','2010-10-23','2010-10-24','2010-10-25','2010-10-26','2010-10-27','2010-10-28','2010-10-29','2010-10-30','2010-10-31','2010-11-01','2010-11-02','2010-11-03','2010-11-04','2010-11-05','2010-11-06','2010-11-07','2010-11-08','2010-11-09','2010-11-10','2010-11-11','2010-11-12','2010-11-13','2010-11-14','2010-11-15','2010-11-16','2010-11-17','2010-11-18','2010-11-19','2010-11-20','2010-11-21','2010-11-22','2010-11-23','2010-11-24','2010-11-25','2010-11-26','2010-11-27','2010-11-28','2010-11-29','2010-11-30','2010-12-01','2010-12-02','2010-12-03','2010-12-04','2010-12-05','2010-12-06','2010-12-07','2010-12-08','2010-12-09','2010-12-10','2010-12-11','2010-12-12','2010-12-13','2010-12-14','2010-12-15','2010-12-16','2010-12-17','2010-12-18','2010-12-19','2010-12-20','2010-12-21','2010-12-22','2010-12-23','2010-12-24','2010-12-25','2010-12-26','2010-12-27','2010-12-28','2010-12-29','2010-12-30','2010-12-31','2011-01-01','2011-01-02','2011-01-03','2011-01-04','2011-01-05','2011-01-06','2011-01-07','2011-01-08','2011-01-09','2011-01-10','2011-01-11','2011-01-12','2011-01-13','2011-01-14','2011-01-15','2011-01-16','2011-01-17','2011-01-18','2011-01-19','2011-01-20','2011-01-21','2011-01-22','2011-01-23','2011-01-24','2011-01-25','2011-01-26','2011-01-27','2011-01-28','2011-01-29','2011-01-30','2011-01-31','2011-02-01','2011-02-02','2011-02-03','2011-02-04','2011-02-05','2011-02-06','2011-02-07','2011-02-08','2011-02-09','2011-02-10','2011-02-11','2011-02-12','2011-02-13','2011-02-14','2011-02-15','2011-02-16','2011-02-17','2011-02-18','2011-02-19','2011-02-20','2011-02-21','2011-02-22','2011-02-23','2011-02-24','2011-02-25','2011-02-26','2011-02-27','2011-02-28','2011-03-01','2011-03-02','2011-03-03','2011-03-04','2011-03-05','2011-03-06','2011-03-07','2011-03-08','2011-03-09','2011-03-10','2011-03-11','2011-03-12','2011-03-13','2011-03-14','2011-03-15','2011-03-16','2011-03-17','2011-03-18','2011-03-19','2011-03-20','2011-03-21','2011-03-22','2011-03-23','2011-03-24','2011-03-25','2011-03-26','2011-03-27','2011-03-28','2011-03-29','2011-03-30','2011-03-31','2011-04-01','2011-04-02','2011-04-03','2011-04-04','2011-04-05','2011-04-06','2011-04-07','2011-04-08','2011-04-09','2011-04-10','2011-04-11','2011-04-12','2011-04-13','2011-04-14','2011-04-15','2011-04-16','2011-04-17','2011-04-18','2011-04-19','2011-04-20','2011-04-21','2011-04-22','2011-04-23','2011-04-24','2011-04-25','2011-04-26','2011-04-27','2011-04-28','2011-04-29','2011-04-30','2011-05-01','2011-05-02','2011-05-03','2011-05-04','2011-05-05','2011-05-06','2011-05-07','2011-05-08','2011-05-09','2011-05-10','2011-05-11','2011-05-12','2011-05-13','2011-05-14','2011-05-15','2011-05-16','2011-05-17','2011-05-18','2011-05-19','2011-05-20','2011-05-21','2011-05-22','2011-05-23','2011-05-24','2011-05-25','2011-05-26','2011-05-27','2011-05-28','2011-05-29','2011-05-30','2011-05-31','2011-06-01','2011-06-02','2011-06-03','2011-06-04','2011-06-05','2011-06-06','2011-06-07','2011-06-08','2011-06-09','2011-06-10','2011-06-11','2011-06-12','2011-06-13','2011-06-14','2011-06-15','2011-06-16','2011-06-17','2011-06-18','2011-06-19','2011-06-20','2011-06-21','2011-06-22','2011-06-23','2011-06-24','2011-06-25','2011-06-26','2011-06-27','2011-06-28','2011-06-29','2011-06-30','2011-07-01','2011-07-02','2011-07-03','2011-07-04','2011-07-05','2011-07-06','2011-07-07','2011-07-08','2011-07-09','2011-07-10','2011-07-11','2011-07-12','2011-07-13','2011-07-14','2011-07-15','2011-07-16','2011-07-17','2011-07-18','2011-07-19','2011-07-20','2011-07-21','2011-07-22','2011-07-23','2011-07-24','2011-07-25','2011-07-26','2011-07-27','2011-07-28','2011-07-29','2011-07-30','2011-07-31','2011-08-01','2011-08-02','2011-08-03','2011-08-04','2011-08-05','2011-08-06','2011-08-07','2011-08-08','2011-08-09','2011-08-10','2011-08-11','2011-08-12','2011-08-13','2011-08-14','2011-08-15','2011-08-16','2011-08-17','2011-08-18','2011-08-19','2011-08-20','2011-08-21','2011-08-22','2011-08-23','2011-08-24','2011-08-25','2011-08-26','2011-08-27','2011-08-28','2011-08-29','2011-08-30','2011-08-31','2011-09-01','2011-09-02','2011-09-03','2011-09-04','2011-09-05','2011-09-06','2011-09-07','2011-09-08','2011-09-09','2011-09-10','2011-09-11','2011-09-12','2011-09-13','2011-09-14','2011-09-15','2011-09-16','2011-09-17','2011-09-18','2011-09-19','2011-09-20','2011-09-21','2011-09-22','2011-09-23','2011-09-24','2011-09-25','2011-09-26','2011-09-27','2011-09-28','2011-09-29','2011-09-30','2011-10-01','2011-10-02','2011-10-03','2011-10-04','2011-10-05','2011-10-06','2011-10-07','2011-10-08','2011-10-09','2011-10-10','2011-10-11','2011-10-12','2011-10-13','2011-10-14','2011-10-15','2011-10-16','2011-10-17','2011-10-18','2011-10-19','2011-10-20','2011-10-21','2011-10-22','2011-10-23'))

**Comment by angelic** [comment]
I plan to work on maker the query smaller. A workaround is to edit _/etc/my.cnf_ and increase _innodb_lock_wait_timeout_

```
innodb_lock_wait_timeout = 500
```
