### ISSUE TITLE
Trouble installing...

### ISSUE THREAD

**Issue by dts** [angelic/schedule_fu#8]
I haven't been able to execute rake db:migrate:schedule_fu (it's not in rake --tasks), I couldn't find any code for it either.  There don't appear to be any rails generators either - once the gem is in the bundle file, I try to run rails generate and it complains that the tables don't exist.

**Comment by angelic** [comment]
Looks like this was overlooked when upgrading it from Rails 2 to Rails 3. I'll look into this soon.

**Comment by angelic** [comment]
The task was renamed. It's now `rake schedule_fu:install:migrations`
